### ISSUE TITLE
No outdoor temperature

### ISSUE THREAD

**Issue by Steffenbvp** [djerik/wavinsentio-ha#35]
After updating to v 18 and .5 integration, the outdoor temperature doesn’t show anymore ..

**Comment by djerik** [comment]
Should be fixed with v0.5.2

**Comment by Steffenbvp** [comment]
Hello again.

after update - the integration doesn't work.

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.wavinsentio
Kilde: helpers/update_coordinator.py:382
integration: Wavin Sentio (dokumentation, problemer)
Første forekomst: 04.04.40 (10 forekomster)
Senest logget: 04.09.00

Unexpected error fetching WavinSentioData data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wavinsentio/__init__.py", line 85, in _async_update_data
    self._device = await self.hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.get_device, self.device_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 205, in get_device
    return Device(device_data)
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 52, in __init__
    self.lastConfig = LastConfig(data.get("lastConfig"))
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 263, in __init__
    self.sentio = Sentio(data.get("sentio"))
                  ~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 270, in __init__
    self.vacationSettings = VacationSettings(data.get("vacationSettings"))
                            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 282, in __init__
    self.vacationModeUntil = datetime.fromisoformat(data.get("vacationModeUntil", ""))
                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: ''

**Comment by djerik** [comment]
I have released 0.5.3 that hopefully fixes this.

I believe this happens if you have never used vacation mode before?

**Comment by Steffenbvp** [comment]
I have never used vacation mode - so perhaps 😀👌🏻

**Comment by Steffenbvp** [comment]
Hey again ..
Still not working

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.wavinsentio
Kilde: helpers/update_coordinator.py:382
integration: Wavin Sentio (dokumentation, problemer)
Første forekomst: 17.35.33 (6 forekomster)
Senest logget: 17.36.26

Unexpected error fetching WavinSentioData data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wavinsentio/__init__.py", line 85, in _async_update_data
    self._device = await self.hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.get_device, self.device_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 205, in get_device
    return Device(device_data)
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 52, in __init__
    self.lastConfig = LastConfig(data.get("lastConfig"))
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 263, in __init__
    self.sentio = Sentio(data.get("sentio"))
                  ~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 270, in __init__
    self.vacationSettings = VacationSettings(data.get("vacationSettings"))
                            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 285, in __init__
    self.vacationModeUntil = datetime.now + timedelta(days=30)
                             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'datetime.timedelta'

**Comment by djerik** [comment]
Sorry for that - fix had a typo that got through my own testing as I cant reproduce with my own system. Please try 0.5.4

**Comment by Steffenbvp** [comment]
Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.wavinsentio
Kilde: helpers/update_coordinator.py:382
integration: Wavin Sentio (dokumentation, problemer)
Første forekomst: 18.24.01 (26 forekomster)
Senest logget: 18.50.21

Unexpected error fetching WavinSentioData data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wavinsentio/__init__.py", line 85, in _async_update_data
    self._device = await self.hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.get_device, self.device_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 205, in get_device
    return Device(device_data)
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 52, in __init__
    self.lastConfig = LastConfig(data.get("lastConfig"))
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 263, in __init__
    self.sentio = Sentio(data.get("sentio"))
                  ~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 270, in __init__
    self.vacationSettings = VacationSettings(data.get("vacationSettings"))
                            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wavinsentio/wavinsentio.py", line 285, in __init__
    self.vacationModeUntil = datetime.now + timedelta(days=30)
                             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'datetime.timedelta'

**Comment by djerik** [comment]
Can I ask you to redownload 0.5.4? I believe there was a problem with the github sync, so the actual change was left out

**Comment by Steffenbvp** [comment]
Logger: homeassistant.util.package
Kilde: util/package.py:159
Første forekomst: 19.36.30 (3 forekomster)
Senest logget: 19.36.31

Unable to install package WavinSentio==0.5.4: × No solution found when resolving dependencies: ╰─▶ Because there is no version of wavinsentio==0.5.4 and you require wavinsentio==0.5.4, we can conclude that your requirements are unsatisfiable.





Logger: homeassistant.setup
Kilde: setup.py:278
Første forekomst: 19.36.31 (1 forekomst)
Senest logget: 19.36.31

Setup failed for custom integration 'wavinsentio': Requirements for wavinsentio not found: ['WavinSentio==0.5.4'].

**Comment by djerik** [comment]
Arrgghhh - sometimes I really hate to follow the guidelines and keep actual integration seperate from HA integration.

dependent Module 0.5.4 had also failed to update.

Please restart

**Comment by Steffenbvp** [comment]
Hello again !

Now it works thanks 🍻

**Comment by djerik** [comment]
@Steffenbvp can you confirm that version 0.5.4 works in general but also that it offers the outdoor temperature entity now?

**Comment by smanf** [comment]
Hi, I can confirm that wit 0.5.4 outdoor temperature is perfectly working together with all the other functions.
The outdoor temperature entity was already offered by the previous version but until your last correction it displayed always None as value. Now it's perfect

<img width="695" height="584" alt="Image" src="https://github.com/user-attachments/assets/84969121-34d8-40fa-9ba4-5ebf5adca09b" />

Thank you very much for your job
